name: Rebuild (security.txt)
on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 1 2-12 *'

jobs:
  rebuild-pages:
    name: Rebuild GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Trigger builds on matching repos
        env:
          GH_USER: ${{ github.repository_owner }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_REBUILD }}
        run: |
          limit=$(date -d 'now + 1 month' +%s)
          gh search code --owner=$GH_USER --match=path security.txt --json repository -q \
            '.[].repository.nameWithOwner' | while read repo; do
              echo "$repo:"
              url=$(gh repo view $repo --json homepageUrl -q .homepageUrl)
              expires=$(curl -Ss "$url/.well-known/security.txt" | grep Expires | cut -f 2 -d ' ')
              echo "security.txt expires $expires"
              [ $(date -d "$expires" +%s) -ge $limit ] || gh api repos/$repo/pages/build -X POST
            done
